version: '3.8'

services:
  db:
    container_name: postgres-user-manager
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
    - ${TYPEORM_PORT}:${TYPEORM_PORT}

  backend:
    container_name: backend-nest-graphql-user-manager
    build:
      context: ./backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${API_PORT}:3001'
    environment:
      - API_PORT=${API_PORT}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db

  frontend:
    container_name: frontend-angular-user-manager
    build:
      context: ./frontend
    depends_on:
      - db
      - backend
    restart: unless-stopped
    ports:
      - '80:80'
